language: shell

services:
  - docker

before_install:
  - sudo /sbin/sysctl -w vm.max_map_count=262144
  - docker pull atzedevries/api-builder
  - docker run --name es -d -e ES_JAVA_OPTS="-Xms512m -Xmx512m" elasticsearch:2.3.5 elasticsearch -Des.cluster.name="nba-cluster" -Des.index.number_of_replicas=0
  - mkdir payload
  - echo GITHUB_USER=$GITHUB_USER > ~/env.file
  - echo GITHUB_PASS=$GITHUB_PASS >> ~/env.file
  - echo "machine github.com" > ~/.netrc
  - echo "\t login $GITHUB_USER" >> ~/.netrc
  - echo "\t password $GITHUB_PASS" >> ~/.netrc
  - git clone https://github.com/naturalis/naturalis_data_api
  - cd naturalis_data_api
  - git checkout $TRAVIS_BRANCH
  - export DOCKER_TAG=$(git describe)
  - cd ~

before_script:
  - sleep 10
  - docker logs es
  - docker exec es curl localhost:9200

script: docker run --rm -v $(pwd)/payload:/payload --env-file env.file --link es:es atzedevries/api-builder /build-nba-service.sh V2_master install-service

after_success:
  - git clone https://github.com/AtzeDeVries/docker-nba-api
  - cd docker-nba-api
  - git checkout -b $DOCKER_TAG
  - cp -fr ~/payload/* ./
  - git add *
  - git commit -a -m 'automatich travis ci build'
  - git push -u origin $DOCKER_TAG
  #- curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "staging"}' -X POST https://registry.hub.docker.com/u/atzedevries/docker-nba-api/trigger/4e4fb6e4-a1c4-45ad-a076-16b38bc2b6b1/
