language: shell

services:
  - docker

env:
  - LASTEST=6d70aff55661c81a537a49e749b85dbde7c6705b

before_install:
  - cd ~
  - sudo /sbin/sysctl -w vm.max_map_count=262144
  - cd api_builder
  - docker build -t atzedevries/api_builder ./
  - cd ~
  - docker run --name es -d -e ES_JAVA_OPTS="-Xms512m -Xmx512m" elasticsearch:5.1.2 elasticsearch -Ecluster.name="nba-cluster" -Enetwork.host="_site_"
  - mkdir ~/payload
  - echo "machine github.com" > ~/.netrc
  - echo "\t login $GITHUB_USER" >> ~/.netrc
  - echo "\t password $GITHUB_PASS" >> ~/.netrc
  - git clone https://github.com/naturalis/naturalis_data_api
  - cd naturalis_data_api
  - git checkout $LATEST
  - export DOCKER_TAG=$(git describe)

before_script:
  - sleep 10
  - docker logs es
  - docker exec es curl localhost:9200
  - cd ~

script: docker run --rm -v $(pwd)/payload:/payload -v $(pwd)/naturalis_data_api:/source --link es:es atzedevries/api-builder /build-nba-service.sh install-service

after_success:
  - git clone https://github.com/AtzeDeVries/docker-nba-api
  - cd docker-nba-api
  - cp -fr ~/payload/* ./
  - git add *
  - git commit -a -m 'automatich travis ci build'
  - git push
