language: shell

branch:
  except:
    - master

services:
  - docker

before_install:
  - docker pull atzedevries/api-builder
  - docker run --name es -d -e ES_JAVA_OPTS="-Xms512m -Xmx512m" elasticsearch:5.1.2 elasticsearch -Ecluster.name='nba-cluster'
  - mkdir payload
  - echo $GITHUB_USER > env.file
  - echo $GITHUB_PASSWORD >> env.file

before_script:
  - sleep 10

script: docker run --rm -v $(pwd)/payload:/payload --env-file env.file --link es:es atzedevries/api-builder /build-nba-service.sh es5 install-service
